fixup! Initial commit

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -1,7 +1,36 @@
 #!/usr/bin/env bash
+# Setups the repository.
 
+# Stop on errors
 set -e
 
-cd "$(dirname "$0")/.."
+cd $(dirname "${0}")/..
 
-python3 -m pip install --requirement requirements.txt
+mkdir -p config
+
+if [ ! -n "$VIRTUAL_ENV" ]; then
+  if [ -x "$(command -v uv)" ]; then
+    uv venv venv
+  else
+    python3 -m venv venv
+  fi
+  source venv/bin/activate
+fi
+
+if ! [ -x "$(command -v uv)" ]; then
+  python3 -m pip install uv
+fi
+
+export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"
+
+# pre-commit install
+uv pip install -r requirements-test.txt
+
+if ! grep -R "logger" config/configuration.yaml >> /dev/null;then
+echo "
+logger:
+  default: info
+  logs:
+    homeassistant.components.cloud: debug
+" >> config/configuration.yaml
+fi
